name: devschoolproject
services:
  app:
    image: devschool/project
    container_name: devschool-project
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/proiect_ing
      - spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
  db:
    image: mysql
    container_name: devschool_db
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proiect_ing
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
